[project]
name = "verotusarvot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4>=4.14.2",
    "httpx[http2,zstd]>=0.28.1",
    "lxml>=6.0.2",
    "polars>=1.34.0",
    "xlrd>=2.0.2",
]
