name: Site

on:
  workflow_dispatch:
  schedule:
    # once every quarter
    - cron: '0 12 5 1,4,7,10 *'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

    - name: git checkout
      uses: actions/checkout@v5

    - name: Install uv
      uses: astral-sh/setup-uv@v7

    - name: Set up Python
      run: uv python install
      
    - name: Build
      run: |
        echo "Deleting ./site and ./data"
        rm -rf ./site ./data
        echo "Creating ./site and ./data"
        mkdir -p ./site ./data
        echo "Downloading data..."
        uv run 01_download_data.py
        echo "Processing data..."
        uv run 02_process_data.py

    - name: Upload static files as artifact
      id: deployment
      uses: actions/upload-pages-artifact@v4
      with:
        path: site/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
